Repository VolkovLabs/business-charts, pull requests merged in 2022-11, with the labels that each got.

#68 Update CI to upload signed artifacts
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
Labels: enhancement

#69 Add Statistics tool (Regression, Clustering, etc.)
  CHANGELOG.md
  README.md
  package.json
  provisioning/dashboards/stats.json
  src/components/EChartsPanel/EChartsPanel.tsx
  src/module.ts
  yarn.lock
Labels: enhancement

#71 Add how to react on mouse events
  CHANGELOG.md
  README.md
Labels: enhancement

#73 Add Monaco Code Editor suggestions for available parameters
  CHANGELOG.md
  README.md
  src/components/EChartsEditor/EChartsEditor.tsx
  src/constants/editor.ts
  src/module.ts
Labels: enhancement

#74 Add Status notification on event handling
  CHANGELOG.md
  README.md
  provisioning/dashboards/panels.json
  src/components/EChartsPanel/EChartsPanel.tsx
  src/constants/editor.ts
Labels: enhancement

#64 Add Baidu map support
  provisioning/dashboards/maps.json
  src/components/EChartsPanel/EChartsPanel.test.tsx
  src/components/EChartsPanel/EChartsPanel.tsx
  src/constants/default.ts
  src/constants/echarts.ts
  src/maps.ts
  src/module.test.ts
  src/module.ts
  src/types/baidu.ts
  src/types/editor.ts
  src/types/index.ts
  src/types/panel.ts
  src/utils.ts
  yarn.lock
Labels: enhancement, priority

#75 Add Tutorial how to load and use Baidu maps
  CHANGELOG.md
  README.md
  src/img/3d.png
  src/img/baidu.png
  src/maps.ts
  src/plugin.json
Labels: enhancement

#77 Limit the url for loading the Baidu map
  CHANGELOG.md
  README.md
  src/constants/default.ts
  src/constants/index.ts
  src/constants/maps.ts
  src/maps.ts
  src/module.ts
  src/types/baidu.ts
Labels: enhancement

#78 Update version 3.7.0
  package.json
Labels: enhancement

#80 Update documentation for Event Handling
  CHANGELOG.md
  README.md
  package.json
Labels: enhancement

#83 Add Histograms, Clustering, Regression tutorial
  CHANGELOG.md
  README.md
  img/ecstat.png
Labels: enhancement

#85 Update documentation how to scale when resize
  README.md
Labels: enhancement

#88 Fix Disabled Format options
  CHANGELOG.md
  src/components/EChartsEditor/EChartsEditor.tsx
  src/constants/editor.ts
Labels: bug

#91 Add Provisioning dashboards for Examples on https://echarts.volkovlabs.io
  CHANGELOG.md
  README.md
  docker-compose.yml
  echarts.volkovlabs.io/bar.json
  echarts.volkovlabs.io/gauge.json
  echarts.volkovlabs.io/geo-map.json
  echarts.volkovlabs.io/home.json
  echarts.volkovlabs.io/line.json
  echarts.volkovlabs.io/pie.json
  echarts.volkovlabs.io/radar.json
  echarts.volkovlabs.io/sankey.json
  echarts.volkovlabs.io/scatter.json
  echarts.volkovlabs.io/sunburst.json
  echarts.volkovlabs.io/treemap.json
  provisioning/dashboards/3d-panels.json
  provisioning/dashboards/maps.json
  provisioning/dashboards/panels.json
  provisioning/dashboards/stats.json
  provisioning/datasources/datasources.yaml
Labels: enhancement
